// <auto-generated />
namespace Gosh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Repsrentig_City_in_Category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Repsrentig_City_in_Category));
        
        string IMigrationMetadata.Id
        {
            get { return "202008171608261_Repsrentig_City_in_Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
